GhidraMCP: com.lauriewired.GhidraMCPPlugin Class Reference
com.lauriewired.GhidraMCPPlugin Class Reference
Classes
class PrototypeResult
Public Member Functions
GhidraMCPPlugin (PluginTool tool)
Program getCurrentProgram ()
void dispose ()
Static Protected Member Functions
static boolean checkFullCommit (HighSymbol highSymbol, HighFunction hfunction)
Private Member Functions
void startServer () throws IOException
String getAllFunctionNames (int offset, int limit)
String getAllClassNames (int offset, int limit)
String listSegments (int offset, int limit)
String listImports (int offset, int limit)
String listExports (int offset, int limit)
String listNamespaces (int offset, int limit)
String listDefinedData (int offset, int limit)
String searchFunctionsByName (String searchTerm, int offset, int limit)
String decompileFunctionByName (String name)
boolean renameFunction (String oldName, String newName)
void renameDataAtAddress (String addressStr, String newName)
String renameVariableInFunction (String functionName, String oldVarName, String newVarName)
String getFunctionByAddress (String addressStr)
String getCurrentAddress ()
String getCurrentFunction ()
String listFunctions ()
Function getFunctionForAddress (Program program, Address addr)
String decompileFunctionByAddress (String addressStr)
String disassembleFunction (String addressStr)
boolean setCommentAtAddress (String addressStr, String comment, int commentType, String transactionName)
boolean setDecompilerComment (String addressStr, String comment)
boolean setDisassemblyComment (String addressStr, String comment)
boolean renameFunctionByAddress (String functionAddrStr, String newName)
void performFunctionRename (Program program, String functionAddrStr, String newName, AtomicBoolean success)
PrototypeResult setFunctionPrototype (String functionAddrStr, String prototype)
void applyFunctionPrototype (Program program, String functionAddrStr, String prototype, AtomicBoolean success, StringBuilder errorMessage)
void addPrototypeComment (Program program, Function func, String prototype)
void parseFunctionSignatureAndApply (Program program, Address addr, String prototype, AtomicBoolean success, StringBuilder errorMessage)
boolean setLocalVariableType (String functionAddrStr, String variableName, String newType)
void applyVariableType (Program program, String functionAddrStr, String variableName, String newType, AtomicBoolean success)
HighSymbol findSymbolByName (ghidra.program.model.pcode.HighFunction highFunction, String variableName)
DecompileResults decompileFunction (Function func, Program program)
void updateVariableType (Program program, HighSymbol symbol, DataType dataType, AtomicBoolean success)
String getXrefsTo (String addressStr, int offset, int limit)
String getXrefsFrom (String addressStr, int offset, int limit)
String getFunctionXrefs (String functionName, int offset, int limit)
String listDefinedStrings (int offset, int limit, String filter)
boolean isStringData (Data data)
String escapeString (String input)
DataType resolveDataType (DataTypeManager dtm, String typeName)
DataType findDataTypeByNameInAllCategories (DataTypeManager dtm, String typeName)
DataType searchByNameInAllCategories (DataTypeManager dtm, String name)
Map< String, String > parseQueryParams (HttpExchange exchange)
Map< String, String > parsePostParams (HttpExchange exchange) throws IOException
String paginateList (List< String > items, int offset, int limit)
int parseIntOrDefault (String val, int defaultValue)
String escapeNonAscii (String input)
void sendResponse (HttpExchange exchange, String response) throws IOException
Private Attributes
HttpServer server
Static Private Attributes
static final String OPTION_CATEGORY_NAME = "GhidraMCP HTTP Server"
static final String PORT_OPTION_NAME = "Server Port"
static final int DEFAULT_PORT = 8080
Detailed Description
GhidraMCP Plugin - Model Context Protocol Server for Ghidra
This plugin creates an HTTP server that exposes Ghidra's analysis capabilities through a RESTful API, enabling AI language models to autonomously perform reverse engineering tasks. The plugin integrates with the CodeBrowser tool and provides comprehensive access to:
Function decompilation and analysis
Symbol and variable management
Memory and data structure examination
Cross-reference analysis
Binary annotation and commenting
Server Lifecycle
The HTTP server automatically starts when the plugin is enabled in CodeBrowser with an active program loaded. The server runs on a configurable port (default: 8080) and remains active while the CodeBrowser session continues.
API Endpoints
The plugin exposes over 20 REST endpoints for comprehensive binary analysis:
/methods - List all functions with pagination
/decompile - Decompile functions by name or address
/renameFunction - Rename functions and variables
/xrefs_to - Analyze cross-references
/strings - Extract and filter string data
Thread Safety
All Ghidra API interactions are properly synchronized using SwingUtilities.invokeAndWait() to ensure thread safety with Ghidra's event dispatch thread.
Author
LaurieWired
Version
1.3.2
Since
Ghidra 11.3.2
See also
ghidra.framework.plugintool.Plugin
com.sun.net.httpserver.HttpServer
Definition at line 109 of file GhidraMCPPlugin.java.
Constructor & Destructor Documentation
GhidraMCPPlugin()
com.lauriewired.GhidraMCPPlugin.GhidraMCPPlugin (PluginTool tool)
Constructs a new GhidraMCP plugin instance and initializes the HTTP server.
This constructor:
Registers the port configuration option in Ghidra's tool options
Starts the embedded HTTP server on the configured port
Creates all REST API endpoint handlers
The server will only function properly when:
A program is loaded in the current CodeBrowser session
The plugin is enabled in the Developer tools configuration
Parameters
tool The Ghidra PluginTool instance that hosts this plugin
Exceptions
IllegalStateException if the HTTP server fails to start
See also
startServer()
Definition at line 143 of file GhidraMCPPlugin.java.
References DEFAULT_PORT, OPTION_CATEGORY_NAME, PORT_OPTION_NAME, and startServer().
Member Function Documentation
addPrototypeComment()
void com.lauriewired.GhidraMCPPlugin.addPrototypeComment (Program program, Function func, String prototype) private
Add a comment showing the prototype being set
Definition at line 1235 of file GhidraMCPPlugin.java.
Referenced by applyFunctionPrototype().
applyFunctionPrototype()
void com.lauriewired.GhidraMCPPlugin.applyFunctionPrototype (Program program, String functionAddrStr, String prototype, AtomicBoolean success, StringBuilder errorMessage) private
Helper method that applies the function prototype within a transaction
Definition at line 1203 of file GhidraMCPPlugin.java.
References addPrototypeComment(), getFunctionForAddress(), and parseFunctionSignatureAndApply().
Referenced by setFunctionPrototype().
applyVariableType()
void com.lauriewired.GhidraMCPPlugin.applyVariableType (Program program, String functionAddrStr, String variableName, String newType, AtomicBoolean success) private
Helper method that performs the actual variable type change
Definition at line 1330 of file GhidraMCPPlugin.java.
References decompileFunction(), findSymbolByName(), getFunctionForAddress(), resolveDataType(), and updateVariableType().
Referenced by setLocalVariableType().
checkFullCommit()
boolean com.lauriewired.GhidraMCPPlugin.checkFullCommit (HighSymbol highSymbol, HighFunction hfunction) static protected
Copied from AbstractDecompilerAction.checkFullCommit, it's protected. Compare the given HighFunction's idea of the prototype with the Function's idea. Return true if there is a difference. If a specific symbol is being changed, it can be passed in to check whether or not the prototype is being affected.
Parameters
highSymbol (if not null) is the symbol being modified
hfunction is the given HighFunction
Returns
true if there is a difference (and a full commit is required)
Definition at line 850 of file GhidraMCPPlugin.java.
Referenced by renameVariableInFunction().
decompileFunction()
DecompileResults com.lauriewired.GhidraMCPPlugin.decompileFunction (Function func, Program program) private
Decompile a function and return the results
Definition at line 1406 of file GhidraMCPPlugin.java.
Referenced by applyVariableType().
decompileFunctionByAddress()
String com.lauriewired.GhidraMCPPlugin.decompileFunctionByAddress (String addressStr) private
Decompile a function at the given address
Definition at line 972 of file GhidraMCPPlugin.java.
References getCurrentProgram(), and getFunctionForAddress().
Referenced by startServer().
decompileFunctionByName()
String com.lauriewired.GhidraMCPPlugin.decompileFunctionByName (String name) private
Decompiles a function by its name and returns the generated C pseudocode.
This method locates a function by name within the current program and uses Ghidra's DecompInterface to generate readable C-like pseudocode. The decompilation process includes:
Function signature analysis
Local variable identification and typing
Control flow reconstruction
High-level language construct generation
Thread Safety: This method uses Ghidra's decompiler interface which is thread-safe for read operations.
Parameters
name The exact name of the function to decompile (case-sensitive)
Returns
The decompiled C pseudocode as a string, or an error message if:
No program is currently loaded
Function with the specified name is not found
Decompilation fails due to analysis issues
See also
DecompInterface#decompileFunction(Function, int, TaskMonitor)
decompileFunctionByAddress(String)
Definition at line 641 of file GhidraMCPPlugin.java.
References getCurrentProgram().
Referenced by startServer().
disassembleFunction()
String com.lauriewired.GhidraMCPPlugin.disassembleFunction (String addressStr) private
Get assembly code for a function
Definition at line 997 of file GhidraMCPPlugin.java.
References getCurrentProgram(), and getFunctionForAddress().
Referenced by startServer().
dispose()
void com.lauriewired.GhidraMCPPlugin.dispose ()
Cleanly shuts down the HTTP server and releases plugin resources.
This method is automatically called by Ghidra when:
The plugin is disabled in the CodeBrowser configuration
The CodeBrowser tool is closed
Ghidra is shutting down
The plugin is being reloaded
Shutdown Process:
Stops the HTTP server with a 1-second grace period for active connections
Nullifies the server reference to prevent further use
Calls the parent dispose method to clean up plugin infrastructure
Thread Safety: This method can be called from any thread and safely handles concurrent access to the server instance.
See also
HttpServer#stop(int)
Plugin#dispose()
Definition at line 1935 of file GhidraMCPPlugin.java.
References server.
escapeNonAscii()
String com.lauriewired.GhidraMCPPlugin.escapeNonAscii (String input) private
Escape non-ASCII chars to avoid potential decode issues.
Definition at line 1862 of file GhidraMCPPlugin.java.
Referenced by listDefinedData().
escapeString()
String com.lauriewired.GhidraMCPPlugin.escapeString (String input) private
Escape special characters in a string for display
Definition at line 1596 of file GhidraMCPPlugin.java.
Referenced by listDefinedStrings().
findDataTypeByNameInAllCategories()
DataType com.lauriewired.GhidraMCPPlugin.findDataTypeByNameInAllCategories (DataTypeManager dtm, String typeName) private
Find a data type by name in all categories/folders of the data type manager This searches through all categories rather than just the root
Definition at line 1700 of file GhidraMCPPlugin.java.
References searchByNameInAllCategories().
Referenced by resolveDataType(), and startServer().
findSymbolByName()
HighSymbol com.lauriewired.GhidraMCPPlugin.findSymbolByName (ghidra.program.model.pcode.HighFunction highFunction, String variableName) private
Find a high symbol by name in the given high function
Definition at line 1392 of file GhidraMCPPlugin.java.
Referenced by applyVariableType().
getAllClassNames()
String com.lauriewired.GhidraMCPPlugin.getAllClassNames (int offset, int limit) private
Definition at line 493 of file GhidraMCPPlugin.java.
References getCurrentProgram(), and paginateList().
Referenced by startServer().
getAllFunctionNames()
String com.lauriewired.GhidraMCPPlugin.getAllFunctionNames (int offset, int limit) private
Retrieves a paginated list of all function names in the current program.
This method scans the program's function manager to collect all function names and returns a subset based on the specified offset and limit parameters. The results are returned as a newline-separated string.
Parameters
offset Starting index for pagination (0-based)
limit Maximum number of function names to return
Returns
Newline-separated string of function names, or error message if no program loaded
See also
#paginateList(List, int, int)
FunctionManager#getFunctions(boolean)
Definition at line 482 of file GhidraMCPPlugin.java.
References getCurrentProgram(), and paginateList().
Referenced by startServer().
getCurrentAddress()
String com.lauriewired.GhidraMCPPlugin.getCurrentAddress () private
Get current address selected in Ghidra GUI
Definition at line 910 of file GhidraMCPPlugin.java.
Referenced by startServer().
getCurrentFunction()
String com.lauriewired.GhidraMCPPlugin.getCurrentFunction () private
Get current function selected in Ghidra GUI
Definition at line 921 of file GhidraMCPPlugin.java.
References getCurrentProgram().
Referenced by startServer().
getCurrentProgram()
Program com.lauriewired.GhidraMCPPlugin.getCurrentProgram ()
Retrieves the currently active program from Ghidra's program manager.
This method provides safe access to the current program being analyzed in the CodeBrowser. It handles cases where no program is loaded or the ProgramManager service is unavailable.
Usage Pattern: This method is called by virtually every API endpoint to ensure operations are performed on the correct program context.
Returns
The currently loaded Program instance, or null if:
No program is currently loaded in CodeBrowser
ProgramManager service is not available
Plugin is not properly initialized
See also
ProgramManager#getCurrentProgram()
PluginTool#getService(Class)
Definition at line 1896 of file GhidraMCPPlugin.java.
Referenced by decompileFunctionByAddress(), decompileFunctionByName(), disassembleFunction(), getAllClassNames(), getAllFunctionNames(), getCurrentFunction(), getFunctionByAddress(), getFunctionXrefs(), getXrefsFrom(), getXrefsTo(), listDefinedData(), listDefinedStrings(), listExports(), listFunctions(), listImports(), listNamespaces(), listSegments(), renameDataAtAddress(), renameFunction(), renameFunctionByAddress(), renameVariableInFunction(), searchFunctionsByName(), setCommentAtAddress(), setFunctionPrototype(), setLocalVariableType(), and startServer().
getFunctionByAddress()
String com.lauriewired.GhidraMCPPlugin.getFunctionByAddress (String addressStr) private
Get function by address
Definition at line 884 of file GhidraMCPPlugin.java.
References getCurrentProgram().
Referenced by startServer().
getFunctionForAddress()
Function com.lauriewired.GhidraMCPPlugin.getFunctionForAddress (Program program, Address addr) private
Gets a function at the given address or containing the address
Returns
the function or null if not found
Definition at line 961 of file GhidraMCPPlugin.java.
Referenced by applyFunctionPrototype(), applyVariableType(), decompileFunctionByAddress(), disassembleFunction(), and performFunctionRename().
getFunctionXrefs()
String com.lauriewired.GhidraMCPPlugin.getFunctionXrefs (String functionName, int offset, int limit) private
Get all references to a specific function by name
Definition at line 1520 of file GhidraMCPPlugin.java.
References getCurrentProgram(), and paginateList().
Referenced by startServer().
getXrefsFrom()
String com.lauriewired.GhidraMCPPlugin.getXrefsFrom (String addressStr, int offset, int limit) private
Get all references from a specific address (xref from)
Definition at line 1481 of file GhidraMCPPlugin.java.
References getCurrentProgram(), and paginateList().
Referenced by startServer().
getXrefsTo()
String com.lauriewired.GhidraMCPPlugin.getXrefsTo (String addressStr, int offset, int limit) private
Get all references to a specific address (xref to)
Definition at line 1449 of file GhidraMCPPlugin.java.
References getCurrentProgram(), and paginateList().
Referenced by startServer().
isStringData()
boolean com.lauriewired.GhidraMCPPlugin.isStringData (Data data) private
Check if the given data is a string type
Definition at line 1585 of file GhidraMCPPlugin.java.
Referenced by listDefinedStrings().
listDefinedData()
String com.lauriewired.GhidraMCPPlugin.listDefinedData (int offset, int limit) private
Definition at line 566 of file GhidraMCPPlugin.java.
References escapeNonAscii(), getCurrentProgram(), and paginateList().
Referenced by startServer().
listDefinedStrings()
String com.lauriewired.GhidraMCPPlugin.listDefinedStrings (int offset, int limit, String filter) private
List all defined strings in the program with their addresses
Definition at line 1559 of file GhidraMCPPlugin.java.
References escapeString(), getCurrentProgram(), isStringData(), and paginateList().
Referenced by startServer().
listExports()
String com.lauriewired.GhidraMCPPlugin.listExports (int offset, int limit) private
Definition at line 532 of file GhidraMCPPlugin.java.
References getCurrentProgram(), and paginateList().
Referenced by startServer().
listFunctions()
String com.lauriewired.GhidraMCPPlugin.listFunctions () private
List all functions in the database
Definition at line 943 of file GhidraMCPPlugin.java.
References getCurrentProgram().
Referenced by startServer().
listImports()
String com.lauriewired.GhidraMCPPlugin.listImports (int offset, int limit) private
Definition at line 521 of file GhidraMCPPlugin.java.
References getCurrentProgram(), and paginateList().
Referenced by startServer().
listNamespaces()
String com.lauriewired.GhidraMCPPlugin.listNamespaces (int offset, int limit) private
Definition at line 550 of file GhidraMCPPlugin.java.
References getCurrentProgram(), and paginateList().
Referenced by startServer().
listSegments()
String com.lauriewired.GhidraMCPPlugin.listSegments (int offset, int limit) private
Definition at line 510 of file GhidraMCPPlugin.java.
References getCurrentProgram(), and paginateList().
Referenced by startServer().
paginateList()
String com.lauriewired.GhidraMCPPlugin.paginateList (List< String > items, int offset, int limit) private
Applies pagination to a list of strings and returns a formatted result.
This utility method implements standard pagination behavior by:
Validating and constraining the offset to valid bounds
Calculating the end index based on offset + limit
Extracting the requested subset of items
Joining the results with newline characters
Pagination Logic:
If offset >= list size, returns empty string
If offset + limit exceeds list size, returns items from offset to end
Negative offsets are treated as 0
Example:
List<String> functions = Arrays.asList("main", "printf", "malloc", "free", "exit");
String page1 = paginateList(functions, 0, 2);  // Returns "main\nprintf"
String page2 = paginateList(functions, 2, 2);  // Returns "malloc\nfree"
String page3 = paginateList(functions, 4, 2);  // Returns "exit"
Parameters
items The complete list of string items to paginate
offset Starting index for pagination (0-based, negative values treated as 0)
limit Maximum number of items to return
Returns
Newline-separated string of the requested items, or empty string if no items in range
See also
List#subList(int, int)
Definition at line 1835 of file GhidraMCPPlugin.java.
Referenced by getAllClassNames(), getAllFunctionNames(), getFunctionXrefs(), getXrefsFrom(), getXrefsTo(), listDefinedData(), listDefinedStrings(), listExports(), listImports(), listNamespaces(), listSegments(), and searchFunctionsByName().
parseFunctionSignatureAndApply()
void com.lauriewired.GhidraMCPPlugin.parseFunctionSignatureAndApply (Program program, Address addr, String prototype, AtomicBoolean success, StringBuilder errorMessage) private
Parse and apply the function signature with error handling
Definition at line 1251 of file GhidraMCPPlugin.java.
Referenced by applyFunctionPrototype().
parseIntOrDefault()
int com.lauriewired.GhidraMCPPlugin.parseIntOrDefault (String val, int defaultValue) private
Parse an integer from a string, or return defaultValue if null/invalid.
Definition at line 1849 of file GhidraMCPPlugin.java.
Referenced by startServer().
parsePostParams()
Map< String, String > com.lauriewired.GhidraMCPPlugin.parsePostParams (HttpExchange exchange) throws IOException private
Parse post body form params, e.g. oldName=foo&newName=bar
Definition at line 1783 of file GhidraMCPPlugin.java.
Referenced by startServer().
parseQueryParams()
Map< String, String > com.lauriewired.GhidraMCPPlugin.parseQueryParams (HttpExchange exchange) private
Parses HTTP query parameters from the request URL into a key-value map.
This method extracts query parameters from the URL (the portion after the '?' character) and decodes them using UTF-8 encoding. It handles URL-encoded parameter values and properly decodes special characters.
Supported Format: ?offset=10&limit=100&filter=test%20string
Example Usage:
// For URL: /methods?offset=50&limit=25
Map<String, String> params = parseQueryParams(exchange);
int offset = parseIntOrDefault(params.get("offset"), 0);  // Returns 50
int limit = parseIntOrDefault(params.get("limit"), 100);  // Returns 25
Parameters
exchange The HTTP exchange containing the request with query parameters
Returns
A map of parameter names to their decoded values. Empty map if no parameters exist. Parameters without values are ignored.
See also
URLDecoder#decode(String, Charset)
parseIntOrDefault(String, int)
Definition at line 1758 of file GhidraMCPPlugin.java.
Referenced by startServer().
performFunctionRename()
void com.lauriewired.GhidraMCPPlugin.performFunctionRename (Program program, String functionAddrStr, String newName, AtomicBoolean success) private
Helper method to perform the actual function rename within a transaction
Definition at line 1151 of file GhidraMCPPlugin.java.
References getFunctionForAddress().
Referenced by renameFunctionByAddress().
renameDataAtAddress()
void com.lauriewired.GhidraMCPPlugin.renameDataAtAddress (String addressStr, String newName) private
Definition at line 718 of file GhidraMCPPlugin.java.
References getCurrentProgram().
Referenced by startServer().
renameFunction()
boolean com.lauriewired.GhidraMCPPlugin.renameFunction (String oldName, String newName) private
Renames a function from its current name to a new user-specified name.
This method performs a thread-safe rename operation by:
Locating the function by its current name
Executing the rename within a Ghidra transaction on the Swing EDT
Marking the new name as USER_DEFINED source type
Committing or rolling back the transaction based on success
Thread Safety: This method uses SwingUtilities.invokeAndWait() to ensure all Ghidra API calls occur on the Event Dispatch Thread, preventing race conditions and maintaining data integrity.
Transaction Management: The rename operation is wrapped in a Ghidra transaction to ensure atomicity - either the rename succeeds completely or is fully reverted.
Parameters
oldName The current name of the function to rename (case-sensitive)
newName The desired new name for the function
Returns
true if the function was successfully renamed, false if no program is loaded, function not found, or rename failed
Exceptions
IllegalArgumentException if either parameter is null or empty
See also
Function#setName(String, SourceType)
SourceType#USER_DEFINED
Program#startTransaction(String)
Definition at line 687 of file GhidraMCPPlugin.java.
References getCurrentProgram().
Referenced by startServer().
renameFunctionByAddress()
boolean com.lauriewired.GhidraMCPPlugin.renameFunctionByAddress (String functionAddrStr, String newName) private
Rename a function by its address
Definition at line 1127 of file GhidraMCPPlugin.java.
References getCurrentProgram(), and performFunctionRename().
Referenced by startServer().
renameVariableInFunction()
String com.lauriewired.GhidraMCPPlugin.renameVariableInFunction (String functionName, String oldVarName, String newVarName) private
Definition at line 752 of file GhidraMCPPlugin.java.
References checkFullCommit(), and getCurrentProgram().
Referenced by startServer().
resolveDataType()
DataType com.lauriewired.GhidraMCPPlugin.resolveDataType (DataTypeManager dtm, String typeName) private
Resolves a data type by name, handling common types and pointer types
Parameters
dtm The data type manager
typeName The type name to resolve
Returns
The resolved DataType, or null if not found
Definition at line 1623 of file GhidraMCPPlugin.java.
References findDataTypeByNameInAllCategories().
Referenced by applyVariableType().
searchByNameInAllCategories()
DataType com.lauriewired.GhidraMCPPlugin.searchByNameInAllCategories (DataTypeManager dtm, String name) private
Helper method to search for a data type by name in all categories
Definition at line 1714 of file GhidraMCPPlugin.java.
Referenced by findDataTypeByNameInAllCategories().
searchFunctionsByName()
String com.lauriewired.GhidraMCPPlugin.searchFunctionsByName (String searchTerm, int offset, int limit) private
Definition at line 589 of file GhidraMCPPlugin.java.
References getCurrentProgram(), and paginateList().
Referenced by startServer().
sendResponse()
void com.lauriewired.GhidraMCPPlugin.sendResponse (HttpExchange exchange, String response) throws IOException private
Definition at line 1901 of file GhidraMCPPlugin.java.
Referenced by startServer().
setCommentAtAddress()
boolean com.lauriewired.GhidraMCPPlugin.setCommentAtAddress (String addressStr, String comment, int commentType, String transactionName) private
Set a comment using the specified comment type (PRE_COMMENT or EOL_COMMENT)
Definition at line 1036 of file GhidraMCPPlugin.java.
References getCurrentProgram().
Referenced by setDecompilerComment(), and setDisassemblyComment().
setDecompilerComment()
boolean com.lauriewired.GhidraMCPPlugin.setDecompilerComment (String addressStr, String comment) private
Set a comment for a given address in the function pseudocode
Definition at line 1066 of file GhidraMCPPlugin.java.
References setCommentAtAddress().
Referenced by startServer().
setDisassemblyComment()
boolean com.lauriewired.GhidraMCPPlugin.setDisassemblyComment (String addressStr, String comment) private
Set a comment for a given address in the function disassembly
Definition at line 1073 of file GhidraMCPPlugin.java.
References setCommentAtAddress().
Referenced by startServer().
setFunctionPrototype()
PrototypeResult com.lauriewired.GhidraMCPPlugin.setFunctionPrototype (String functionAddrStr, String prototype) private
Set a function's prototype with proper error handling using ApplyFunctionSignatureCmd
Definition at line 1174 of file GhidraMCPPlugin.java.
References applyFunctionPrototype(), and getCurrentProgram().
Referenced by startServer().
setLocalVariableType()
boolean com.lauriewired.GhidraMCPPlugin.setLocalVariableType (String functionAddrStr, String variableName, String newType) private
Set a local variable's type using HighFunctionDBUtil.updateDBVariable
Definition at line 1305 of file GhidraMCPPlugin.java.
References applyVariableType(), and getCurrentProgram().
Referenced by startServer().
startServer()
void com.lauriewired.GhidraMCPPlugin.startServer () throws IOException private
Initializes and starts the embedded HTTP server with all API endpoints.
This method creates an HTTP server instance and registers handlers for all supported REST API endpoints. The server supports:
Function Analysis Endpoints:
GET /methods - List functions with pagination
POST /decompile - Decompile function by name
GET /decompile_function?address=0x... - Decompile by address
GET /disassemble_function?address=0x... - Get assembly listing
Symbol Management Endpoints:
POST /renameFunction - Rename functions
POST /renameVariable - Rename local variables
POST /set_function_prototype - Set function signatures
Analysis and Reference Endpoints:
GET /xrefs_to?address=0x... - Find references to address
GET /xrefs_from?address=0x... - Find references from address
GET /strings - List string data with filtering
Commenting and Annotation:
POST /set_decompiler_comment - Add pseudocode comments
POST /set_disassembly_comment - Add assembly comments
The server runs on a separate thread to avoid blocking Ghidra's UI thread. All endpoints return plain text responses with UTF-8 encoding.
Exceptions
IOException if the server cannot bind to the configured port
See also
sendResponse(HttpExchange, String)
parseQueryParams(HttpExchange)
Definition at line 204 of file GhidraMCPPlugin.java.
References decompileFunctionByAddress(), decompileFunctionByName(), DEFAULT_PORT, disassembleFunction(), findDataTypeByNameInAllCategories(), getAllClassNames(), getAllFunctionNames(), getCurrentAddress(), getCurrentFunction(), getCurrentProgram(), com.lauriewired.GhidraMCPPlugin.PrototypeResult.getErrorMessage(), getFunctionByAddress(), getFunctionXrefs(), getXrefsFrom(), getXrefsTo(), com.lauriewired.GhidraMCPPlugin.PrototypeResult.isSuccess(), listDefinedData(), listDefinedStrings(), listExports(), listFunctions(), listImports(), listNamespaces(), listSegments(), OPTION_CATEGORY_NAME, parseIntOrDefault(), parsePostParams(), parseQueryParams(), PORT_OPTION_NAME, renameDataAtAddress(), renameFunction(), renameFunctionByAddress(), renameVariableInFunction(), searchFunctionsByName(), sendResponse(), server, setDecompilerComment(), setDisassemblyComment(), setFunctionPrototype(), and setLocalVariableType().
Referenced by GhidraMCPPlugin().
updateVariableType()
void com.lauriewired.GhidraMCPPlugin.updateVariableType (Program program, HighSymbol symbol, DataType dataType, AtomicBoolean success) private
Apply the type update in a transaction
Definition at line 1426 of file GhidraMCPPlugin.java.
Referenced by applyVariableType().
Member Data Documentation
DEFAULT_PORT
final int com.lauriewired.GhidraMCPPlugin.DEFAULT_PORT = 8080 static private
Default port number for the HTTP server (8080)
Definition at line 121 of file GhidraMCPPlugin.java.
Referenced by GhidraMCPPlugin(), and startServer().
OPTION_CATEGORY_NAME
final String com.lauriewired.GhidraMCPPlugin.OPTION_CATEGORY_NAME = "GhidraMCP HTTP Server" static private
Configuration category name for tool options
Definition at line 115 of file GhidraMCPPlugin.java.
Referenced by GhidraMCPPlugin(), and startServer().
PORT_OPTION_NAME
final String com.lauriewired.GhidraMCPPlugin.PORT_OPTION_NAME = "Server Port" static private
Configuration option name for the server port setting
Definition at line 118 of file GhidraMCPPlugin.java.
Referenced by GhidraMCPPlugin(), and startServer().
server
HttpServer com.lauriewired.GhidraMCPPlugin.server private
The embedded HTTP server instance that handles all API requests
Definition at line 112 of file GhidraMCPPlugin.java.
Referenced by dispose(), and startServer().
The documentation for this class was generated from the following file:
src/main/java/com/lauriewired/GhidraMCPPlugin.java